// This file is automatically generated. Do not edit it directly.
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getGoTrueClient } from "@/utils/goTrueClient";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// DEV: optional debug for local development only
if (import.meta.env.DEV) {
  console.debug("SUPABASE ENV", {
    url: SUPABASE_URL,
    hasKey: !!SUPABASE_ANON_KEY,
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase: SupabaseClient<Database> = getGoTrueClient();
